server:
  port: 9876
random-org:
  jsonrpc: "2.0"
  method: "generateIntegers"
  apiKey: "76267b0d-cef1-4aaa-beea-ecec3828a57b"
  min: 1
  max: 10000
  n: 1
spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: add_app